[site]
title = "æ–°å®¿å¾¡è‹‘.dev"
description = "æ–°å®¿å¾¡è‹‘.devã¯ã€æ–°å®¿å¾¡è‹‘ãŒå¥½ããªã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã®ãŸã‚ã®åœ°åŸŸã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã§ã™ã€‚æ–°å®¿å¾¡è‹‘å†…ã®ã‚³ãƒ¯ãƒ¼ã‚­ãƒ³ã‚°ã‚¹ãƒšãƒ¼ã‚¹ãªã©ã‚’æ´»ç”¨ã—ãŸã‚¤ãƒ™ãƒ³ãƒˆé–‹å‚¬ã‚’ç›®çš„ã¨ã—ã¦ã„ã¾ã™ã€‚"
since = "2024"

[[site.contents]]
title = "ãƒˆãƒƒãƒ—"
path = "/"

[[site.contents]]
title = "ã‚¤ãƒ™ãƒ³ãƒˆæƒ…å ±"
path = "/events"

[[site.contents]]
title = "ã‚¤ãƒ™ãƒ³ãƒˆè¡Œå‹•è¦ç¯„"
path = "/event-code-of-conduct"

[[site.contents]]
title = "é–‹å‚¬ãƒ¬ãƒãƒ¼ãƒˆ"
path = "/reports"

[[site.links]]
name = "Connpassã‚°ãƒ«ãƒ¼ãƒ—"
url = "https://shinjukugyoen.connpass.com/"

[[site.links]]
name = "Discordã‚µãƒ¼ãƒãƒ¼"
url = "https://discord.com/invite/eYPCYu2zxX"

[[site.links]]
name = "ğ•ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚° (#æ–°å®¿å¾¡è‹‘dev)"
url = "https://x.com/search?q=%23%E6%96%B0%E5%AE%BF%E5%BE%A1%E8%8B%91dev"
