title = "æ–°å®¿å¾¡è‹‘.dev"
description = "æ–°å®¿å¾¡è‹‘.devã¯ã€æ–°å®¿å¾¡è‹‘ãŒå¥½ããªã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã®ãŸã‚ã®åœ°åŸŸã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã§ã™ã€‚æ–°å®¿å¾¡è‹‘å†…ã®ã‚³ãƒ¯ãƒ¼ã‚­ãƒ³ã‚°ã‚¹ãƒšãƒ¼ã‚¹ãªã©ã‚’æ´»ç”¨ã—ãŸã‚¤ãƒ™ãƒ³ãƒˆé–‹å‚¬ã‚’ç›®çš„ã¨ã—ã¦ã„ã¾ã™ã€‚"
since = "2024"

[[contents]]
title = "ãƒˆãƒƒãƒ—"
path = "/"

[[contents]]
title = "æ–°å®¿å¾¡è‹‘.devã«ã¤ã„ã¦"
path = "/about"

[[contents]]
title = "ã‚¤ãƒ™ãƒ³ãƒˆæƒ…å ±"
path = "/events"

[[contents]]
title = "ã‚¤ãƒ™ãƒ³ãƒˆè¡Œå‹•è¦ç¯„"
path = "/event-code-of-conduct"

[[contents]]
title = "é–‹å‚¬ãƒ¬ãƒãƒ¼ãƒˆ"
path = "/reports"

# é–¢é€£ãƒªãƒ³ã‚¯

[[links]]
name = "GitHubãƒªãƒã‚¸ãƒˆãƒª"
url = "https://github.com/shinjukugyoen-dev/shinjukugyoen-dev.github.io"
description = "æƒ…å ±ã‚µã‚¤ãƒˆã®ç®¡ç†ã¨ã‚¤ãƒ™ãƒ³ãƒˆã®ä¼ç”»ã‚’è¡Œãªã£ã¦ã„ã¾ã™"

[[links]]
name = "Connpassã‚°ãƒ«ãƒ¼ãƒ—"
url = "https://shinjukugyoen.connpass.com/"
description = "ã‚¤ãƒ™ãƒ³ãƒˆå‚åŠ è€…ã®å‹Ÿé›†ã«åˆ©ç”¨ã—ã¦ã„ã¾ã™"

[[links]]
name = "Discordã‚µãƒ¼ãƒ"
url = "https://discord.com/invite/eYPCYu2zxX"
description = "ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ã‚³ãƒŸãƒ¥ãƒ‹ã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã®å ´ã¨ã—ã¦åˆ©ç”¨ã—ã¦ã„ã¾ã™"

[[links]]
name = "ğ•ãƒãƒƒã‚·ãƒ¥ã‚¿ã‚° (#æ–°å®¿å¾¡è‹‘dev)"
url = "https://x.com/search?q=%23%E6%96%B0%E5%AE%BF%E5%BE%A1%E8%8B%91dev"
description = "ã‚¤ãƒ™ãƒ³ãƒˆå½“æ—¥ã®ç››ã‚Šä¸Šã’ã«åˆ©ç”¨ã—ã¦ã„ã¾ã™"

[[links]]
name = "mixi2ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£"
url = "https://mixi.social/communities/96602d7e-dea6-4325-ba69-d749416dbe9a/about"
description = "ã‚¤ãƒ™ãƒ³ãƒˆå‘ŠçŸ¥ã‚’è¡Œãªã£ã¦ã„ã¾ã™ (ã¨ã‚Šã‚ãˆãšä½œæˆã—ã¾ã—ãŸ)"
